### ISSUE TITLE
AttributeError: 'module' object has no attribute 'VarsModule'

### ISSUE THREAD

**Issue by joaocc** [Gu1/ansible-lxc-remote#1]
Hi,
I am testing the plugin, but I get this error when I add it to the library path (ansible v1.9.2).

```
    Traceback (most recent call last):
      File "/usr/bin/ansible", line 197, in <module>
        (runner, results) = cli.run(options, args)
      File "/usr/bin/ansible", line 121, in run
        inventory_manager = inventory.Inventory(options.inventory, vault_password=vault_pass)
      File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 141, in __init__
        self._vars_plugins = [ x for x in utils.plugins.vars_loader.all(self) ]
      File "/usr/lib/pymodules/python2.7/ansible/utils/plugins.py", line 233, in all
        yield getattr(self._module_cache[path], self.class_name)(*args, **kwargs)
    AttributeError: 'module' object has no attribute 'VarsModule'
```

From comparing the code of _ssh.py in your module to ssh.py in ansible v1.9.2, it looks like the module doesn't support the become_user changes.

Any ideas?
Thx

**Comment by joaocc** [comment]
The relevant commit seems to be Commit: bce4bb2ce29917967707552bacb245ad24856c53 [bce4bb2]

**Comment by Gu1** [comment]
I haven't tested this module in newer versions of ansible (> 1.7.x).
I will try to have a look soon and see how hard it would be to make it work.

**Comment by Gu1** [comment]
@joaocc: I pushed some change that seem to make it work for me on ansible 1.9.
Didn't have time to test it thoroughly

```
$ cat inventory 
test_container ansible_ssh_user=host_user ansible_ssh_host=192.168.1.20 ansible_ssh_port=22 ansible_connection=lxc_remote
$ ansible -b --ask-become-pass --become-user host_root -u container_root -i inventory test_container -m shell -a 'date'
SUDO password: 
test_container | success | rc=0 >>
Fri Jul 24 15:36:35 CEST 2015
```

Could you please tell me if it works for you ?

**Comment by joaocc** [comment]
Hi,
Thanks for the prompt update.
I still get the same error message when running this...

```
ansible -i /etc/ansible/mysite/inv --list-hosts all
```

Additional data:
- the controller machine is Ubuntu 14.04 running ansible 1.9.2-1ppa~trusty
- the remote LXC host is a Ubuntu 14.04 running lxc 1.0.7-0ubuntu0.2

My ansible_hosts file is

```
remotelxchost       ansible_connection=ssh ansible_ssh_port=22000   ansible_ssh_user=root      ansible_ssh_host=remotelxchost.domaindomain.com
lxcguestremote        ansible_connection=lxc_remote ansible_ssh_host=remotelxchost.domaindomain.com ansible_ssh_port=22000 ansible_ssh_user=root
```

Thanks

**Comment by Gu1** [comment]
The weird thing is that the traceback you pasted talks about a vars plugin (which this plugin is not).
How did you declare it in ansible ? Did you set the `connection_plugins` option to the path of this plugin as instructed in the README ?

**Comment by joaocc** [comment]
Hi.
Well, the previous message was because I had listed /etc/ansible/commons/library/ under all the plugins variables.
Setting it only in connection_plugins sorted that message out.
